#!/usr/bin/env bash

# shellcheck disable=1090,1091,2046,2048,2086,2206,2155

set -aeu

INSTALLDIR=$PWD/conda
MAKE="make=4.4.*"
UWTOOLS="uwtools=2.13.*"

# In all functions, make variables local unless they are either intended for global use, or set in
# a subshell that exits at the end of the function.

conda_activate() {
  local env=$1
  source $INSTALLDIR/etc/profile.d/conda.sh
  # Activation scripts shipped with conda packages may contain statements either expanding undefined
  # variables or exiting with error status, so temporarily disable the checks for these conditions,
  # then enable again.
  set +eu
  conda activate $env
  set -eu
}

conda_create() {
  local name=$1
  conda_activate base
  msg Creating environment: $name
  # In each runtime virtual environment, "make format" requires jq to format JSON Schema files;
  # invoking make targets requires make itself; and driver execution and config management require
  # uwtools, so install those.
  conda create -y -q -c ufs-community -n $* jq $MAKE $UWTOOLS
  (
    # When runtime virtual environments are activated, set XDG_CACHE_HOME so that pip caches package
    # files in the runtime area, rather than in the user's home directory, which might impact their
    # quota. When deactivated, environments should reset or unset this value, as appropriate.
    conda_activate $name
    dir_activate=$CONDA_PREFIX/etc/conda/activate.d
    mkdir -pv $dir_activate
    cat <<EOF >$dir_activate/eagle.sh
if [[ -v XDG_CACHE_HOME ]]; then
  export EAGLE_OLD_XDG_CACHE_HOME=\$XDG_CACHE_HOME
fi
export XDG_CACHE_HOME=\$_CONDA_ROOT/cache
EOF
    dir_deactivate=$CONDA_PREFIX/etc/conda/deactivate.d
    mkdir -pv $dir_deactivate
    cat <<EOF >$dir_deactivate/eagle.sh
unset XDG_CACHE_HOME
if [[ -v EAGLE_OLD_XDG_CACHE_HOME ]]; then
  export XDG_CACHE_HOME=\$EAGLE_OLD_XDG_CACHE_HOME
  unset EAGLE_OLD_XDG_CACHE_HOME
fi
EOF
  )
}

conda_create_base() {
  true
}

conda_create_data() {
  local name=data
  conda_env_exists $name && return || true
  conda_create $name impi_rt=2021.13.* mpi4py=4.1.* numpy=1.26.4 pandas=2.3.3 types-pyyaml ufs2arco=0.18.*
  (
    conda_activate $name
    dir_activate=$CONDA_PREFIX/etc/conda/activate.d
    mkdir -pv $dir_activate
    cat <<EOF >>$CONDA_PREFIX/etc/conda/activate.d/eagle.sh
if [[ -v FI_PSM3_UUID ]]; then
  export EAGLE_OLD_FI_PSM3_UUID=\$FI_PSM3_UUID
fi
export FI_PSM3_UUID=eagle
EOF
    dir_deactivate=$CONDA_PREFIX/etc/conda/deactivate.d
    mkdir -pv $dir_deactivate
    cat <<EOF >>$CONDA_PREFIX/etc/conda/deactivate.d/eagle.sh
unset FI_PSM3_UUID
if [[ -v EAGLE_OLD_FI_PSM3_UUID ]]; then
  export FI_PSM3_UUID=\$EAGLE_OLD_FI_PSM3_UUID
  unset EAGLE_OLD_FI_PSM3_UUID
fi
EOF
  )
  pip_install $name anemoi-datasets==0.5.* anemoi-graphs==0.6.*
}

conda_create_inference() {
  local name=inference
  conda_env_exists $name && return || true
  (
    CONDA_OVERRIDE_CUDA=$(cuda_release) conda_create $name flash-attn=2.8.* numpy=2.2.6 python=3.12
    conda_activate $name
    write_anemoi_activation_scripts
  )
  pip_install $name anemoi-inference==0.7.* anemoi-models==0.9.* eagle-tools
}

conda_create_training() {
  local name=training
  conda_env_exists $name && return || true
  (
    CONDA_OVERRIDE_CUDA=$(cuda_release) conda_create $name flash-attn=2.8.* numpy=1.26.4 python=3.12
    conda_activate $name
    write_anemoi_activation_scripts
  )
  pip_install $name anemoi-models==0.9.* anemoi-training==0.6.*
}

conda_create_vx() {
  local name=vx
  conda_env_exists $name && return || true
  conda_create $name -c oar-gsl python=3.13 wxvx=0.7.* xesmf
  pip_install $name eagle-tools
}

conda_env_exists() {
  name=$1
  (
    conda_activate base
    if conda env list --json | jq -r .envs_details[].name | grep -q "^$name$"; then
      msg Found existing conda environment: $name
      exit 0
    fi
    exit 1
  )
}

conda_install() {
  local name=$1
  shift
  (
    conda_activate $name
    set +eu
    conda install -y -q "$@"
    set -eu
  )
}

conda_install_devpkgs() {
  local name=$1
  local devpkgs=( $MAKE mypy=1.19.* ruff=0.14.* )
  msg Installing dev packages into environment: $name
  conda_install $name "${devpkgs[@]}"
}

cuda_command_file() {
  local path val
  val=${ARGS[cudascript]}
  path=$val
  test -e $path || path=$(dirname $(readlink -f $0))/cuda/$val
  echo $path
}

cuda_release() {
  (
    source $(cuda_command_file)
    nvcc --version | grep release | sed -E 's/^.*release ([0-9]+).*/\1/'
  )
}

install_conda() {
  if [[ -d $INSTALLDIR ]]; then
    msg Found existing conda installation: $INSTALLDIR
    return
  fi
  local ver=25.9.1-0
  local installer=Miniforge3-$ver-$(uname -s)-$(uname -p).sh
  local url=https://github.com/conda-forge/miniforge/releases/download/$ver/$installer
  msg Installing conda
  wget -nv $url
  bash $installer -bfp $INSTALLDIR
  rm -v $installer
  conda_install base -c ufs-community $UWTOOLS
}

msg() {
  echo -e "=> $*"
}

parse_kvargs() {
  local arg key required val
  declare -g -A ARGS
  for arg in "$@"; do
    IFS="=" read -r key val <<< $arg
    ARGS[$key]=$val
  done
  required="cudascript"
  for arg in $required; do
    test -z "${ARGS[$arg]:-}" && echo Argument $arg= missing && exit 1
  done
  export ARGS
}

pip_install() {
  local name=$1
  shift
  (
    conda_activate $name
    pip install "$@"
  )
}

write_anemoi_activation_scripts() {
    cat <<EOF >>$CONDA_PREFIX/etc/conda/activate.d/eagle.sh
modules="\$(module --terse list 2>/dev/null | grep -v 'No modules loaded' | tr '\n' ' ')"
if [[ -n "\$modules" ]]; then
  export EAGLE_OLD_MODULES="\$modules"
fi
$(cat $(cuda_command_file))
EOF
    cat <<EOF >>$CONDA_PREFIX/etc/conda/deactivate.d/eagle.sh
module purge 2>/dev/null
if [[ -v EAGLE_OLD_MODULES ]]; then
  module load \$EAGLE_OLD_MODULES
  unset EAGLE_OLD_MODULES
fi
EOF
}

parse_kvargs "$@"
install_conda
conda_install base shellcheck $UWTOOLS
environments=( base data training inference vx )
for name in ${environments[*]}; do
  conda_create_$name
  test -v EAGLE_DEV && conda_install_devpkgs $name
done
msg Done
